version: 2

sources:
  - name: bourbon_bowl_github
    database: bourbon-bowl
    schema: github

    tables:
      - name: commit
  
  - name: bourbon_bowl_test
    database: bourbon-bowl
    schema: test
    tables:
      - name: facts